auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /tmp/loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

memberlist:
  join_members: []

pattern-distributor:
  ring:
    kvstore:
      store: inmemory

pattern-ingester:
  chunk_target_size: 1572864    # Target size of chunks in bytes
  max_transfer_retries: 3       # Maximum number of retries for transferring log batches
  lifecycler:
    join_after: 0s
    heartbeat_period: 5s
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

pattern-querier:
  query_ingesters_within: 2h
  query_store_after: 24h

frontend:
  address: 127.0.0.1
  log_queries_longer_than: 5s
  compress_responses: true

query_range:
  split_queries_by_interval: 24h
  align_queries_with_step: true

table_manager:
  retention_deletes_enabled: true
  retention_period: 672h # 28 days

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_streams_per_user: 10000
  max_global_streams_per_user: 50000

schema_config:
  configs:
    - from: 2024-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/boltdb-cache
    cache_ttl: 24h
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  working_directory: /var/loki/compactor
  shared_store: filesystem

ruler:
  storage:
    type: local
    local:
      directory: /var/loki/rules

client:
  backoff_config:
    min_period: 500ms   # Minimum backoff period
    max_period: 5s      # Maximum backoff period
    max_retries: 3      # Number of retries for sending log batches
